Just add a retry before really throwing a FastCgiCommunicationFailed exception.
brefphp/bref pull request #1758
Opened 2024-03-15 12:08 UTC by wysow

Hello there!

This PR only to start a discussion to try to find a solution to this kind of random errors:

```
Error communicating with PHP-FPM to read the HTTP response. Bref will restart PHP-FPM now. Original exception message: hollodotme\FastCGI\Exceptions\ReadFailedException Stream got blocked, or terminated.
```

I'm pretty sure something smarter can be achieved but manually testing this for a few minutes now and only got 200 responses and no more 500...

2024-03-15 12:10 UTC, lguilbert approved these changes

2024-03-15 12:30 UTC, wysow commented
Here is something interesting about this: https://github.com/hollodotme/fast-cgi-client/issues/68#issuecomment-1207839792

2024-03-17 15:22 UTC, mnapoli commented
What if the request is updating something in the database, or sending emails for example. That could run the same request/action twice, which might not be a good thing 🤔

How often do you get these errors?

2024-03-17 16:58 UTC, GrahamCampbell requested changes
Re-trying seems like a bad idea to me. It's usual for clients to retry safe requests, not for proxy layers to do it, unless the error is for sure retriable such as an edge load balancer retrying a TLS handshake.

2024-03-18 09:08 UTC, wysow commented
@mnapoli Can't really tell how often it appears on the long run, but when I do some manual testing I sometimes get 50% error rate.... So that's a lot...

I know that retrying is a bit crappy but the fact is that in all the error I get in logs our code is never executed at all, everything happens on Bref side... So for us no problem to do a retry, and then we have a 0% error rate with manual testing.

2024-03-18 09:11 UTC, GrahamCampbell commented
50% error rate smells like something else is borked. Is it always failing after the first invoke?

2024-03-18 09:16 UTC, wysow commented
That's only my own feeling but yes I'm pretty sure it's always after the first invoke...

2024-03-18 09:17 UTC, wysow commented
And to add more context, we did NOT see this behavior on workers or console lambdas (working with Symfony)

2024-03-18 09:21 UTC, wysow commented
Just looked at the numbers of the last days with bref dashboard and I can see a 6-7% error rate on entire days.

2024-03-18 10:47 UTC, mnapoli commented
That is really weird, something else must be at play here. A 6-7% error rate would be affecting all Bref users if that was a global Bref problem.

I'd start looking at ways to pinpoint the problem:

- extra PHP extensions?
- out of memory?
- spawning sub-processes from PHP?
- timing out?
- try to see if it happens on a specific HTTP route?
- trying to reproduce with an empty project?

2024-03-18 14:55 UTC, wysow commented
Here a first list of answers, will keep you posted with others answers when I get them:

>     * extra PHP extensions?
 -> Yes, on this project we have redis and mongodb

>     * out of memory?
-> I'm pretty sure this is not the case as the error is really fast at the execution start (few milliseconds). We are using 2048Mo lambda memory size on this project.  

>     * spawning sub-processes from PHP?
-> this project is an API using bref 8.2 fpm layer and symfony so this is not the case for me here.

>     * timing out?
-> Like I said the error is really fast at the execution start so not the case either...

>     * try to see if it happens on a specific HTTP route?
-> will do more testing but I saw it on every HTTP route (GET mainly)

>     * trying to reproduce with an empty project?
-> Will try and keep you posted.

2024-03-18 15:08 UTC, mnapoli commented
Would be interesting to see too if this happens on cold starts. If not, is the request _before_ successful? Times out? Could fill the memory? (or any other reason it could leave the environment in a broken state)

Also nothing specific/exotic, like using Symfony Runtime, setting a non-standard handler, etc.

2024-03-18 15:50 UTC, wysow commented
> Would be interesting to see too if this happens on cold starts. If not, is the request _before_ successful? Times out? Could fill the memory? (or any other reason it could leave the environment in a broken state)
> 
> Also nothing specific/exotic, like using Symfony Runtime, setting a non-standard handler, etc.

As far as I manually tested this is not happening on cold starts, and the previous request is always successful. No timeout, not full memory... Nothing visible at least....

2024-03-19 15:22 UTC, wysow commented
Here is the raw log we got when this problem occur:
```
Error communicating with PHP-FPM to read the HTTP response. Bref will restart PHP-FPM now. Original exception message: hollodotme\FastCGI\Exceptions\ReadFailedException Stream got blocked, or terminated.

WARNING: [pool default] child 19 exited on signal 11 (SIGSEGV) after 424.432414 seconds from start
```

Here the 424 seconds is really weird as the behavior in an API client is really fast...

2024-03-19 17:23 UTC, wysow commented
> File `php.ini` custom in our projet with this content:
> 
> ```
> extension=intl
> ```

@mnapoli sorry this is not the right `php.ini` file... Here is the good one:
```
extension=mongodb
extension=redis
opcache.enable_cli=0
```

2024-06-18 09:39 UTC, mnapoli commented
Closing for now as we know that's unfortunately not a solution we can use since it may retry valid requests (non-idempotent) on occasion.

2024-06-18 09:39 UTC, closed without merging