fix: key was missing in kafka record
brefphp/bref pull request #1862
Opened 2024-09-20 00:26 UTC by falnyr

Added a getter for missing key property because it was missing.

As per the official SDK for Java: https://github.com/aws/aws-lambda-java-libs/blob/main/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/KafkaEvent.java

2024-09-20 08:37 UTC, mnapoli commented
Thanks, can you update the tests too?

2024-09-22 18:49 UTC, falnyr commented
Thanks for letting me know @mnapoli. Added now.

2024-09-23 12:20 UTC, mnapoli commented
Can you fix the build?

2024-09-23 12:22 UTC, GrahamCampbell requested changes

2024-09-23 12:22 UTC, GrahamCampbell commented on src/Event/Kafka/KafkaRecord.php
> +
The issue is that this line contains 4 spaces. It should contain 0.

2024-09-25 08:19 UTC, merged