bref cli : simplify usage of <function-name>
brefphp/bref pull request #955
Opened 2021-06-16 21:23 UTC by Guillaume-Rossignol

This should solve #125.
Bonus : if you have multiple function to use in cli, you could use the "short name" `hello` instead of the full name `myapp-dev-hello`

2021-09-03 22:23 UTC, t-richard requested changes
Thanks for this PR @Guillaume-Rossignol!

It has been stale for a while but I think it's still a great improvement to the overall experience when working with console. 

I added some comments, let me know what you think 🙂

2021-09-03 22:23 UTC, t-richard commented on bref
> +    // Replace short function name (like in serverless.yml) by full qualified name
```suggestion
    // Replace short function name (like in serverless.yml) by fully qualified name
```

2021-09-03 22:23 UTC, t-richard commented on docs/runtimes/console.md
> +`<function-name>` is the name of the function that was define in `serverless.yml`. In our example above that would be `hello`.
```suggestion
`<function-name>` is the name of the function that was defined in `serverless.yml`. In our example above that would be `hello`.
```

2021-09-03 22:23 UTC, t-richard commented on bref
> +            $function= getFunctionWithConsoleLayer();
```suggestion
            $function = getFunctionWithConsoleLayer();
```

2021-09-03 22:23 UTC, t-richard commented on bref
> +    $serverlessInfo =getServerlessInfo($stage, $profile, $io);
```suggestion
    $serverlessInfo = getServerlessInfo($stage, $profile, $io);
```

2021-09-03 22:23 UTC, t-richard commented on bref
> +    }catch (\Exception $e) {
```suggestion
    } catch (\Exception $e) {
```

2021-09-03 22:23 UTC, t-richard commented on bref
> +    $command = ['serverless', 'info', '--aws-profile', $profile];
```suggestion
    $command = ['serverless', 'info'];
    
    if ($profile !== null) {
        $command += ['--aws-profile', $profile]
    }
```

2022-03-05 12:56 UTC, mnapoli commented
Closing for now as the Serverless Framework output isn't stable (e.g. with the new v3). Probably a new (more robust) approach would be to implement these features in the Serverless Framework plugin, it's made exactly for these kinds of use cases.

Thank you @Guillaume-Rossignol ❤️

2022-03-05 12:56 UTC, closed without merging